#!/usr/bin/php
<?php

if ($argv[1] === '-h' || $argv[1] === '--help') {
    $help = "
 -h  help, show this message
 -r  read string
 -u  url encode (default - 'url decode')
 -e  use 'UTF-8 encode' (default - 'UTF-8 decode')
\n";
    echo $help;
    exit(0);
}


if (!empty($argv[1]) && in_array('-r', $argv) ) {
    $str = readline("Enter string : ");

    echo decode($str);

    return;
}



if (empty($argv[1])) {
    $filename = readline("Enter filename : ");
} else {
    $filename = $argv[1];
}


$src = file_get_contents(getcwd() . '/' . $filename);

echo decode($src);


/*
 | FUNCTIONS
*/


function decode($str) {

    $argv = $_SERVER['argv'];
    $encode = in_array('-e', $argv);

    if (in_array('-u', $argv)) 
    {
        echo "URL decode:\n";
        return (
            $encode 
                ? urlencode($str) 
                : urldecode($str)
            ) . "\n";
    }

    return jdecoder($str, $encode);
}




/**
 * @param  String 
 * @return String 
 */
function jdecoder($json_str, $flip = false) {
  $cyr_chars = array (
    '\u0430' => 'а', '\u0410' => 'А',
    '\u0431' => 'б', '\u0411' => 'Б',
    '\u0432' => 'в', '\u0412' => 'В',
    '\u0433' => 'г', '\u0413' => 'Г',
    '\u0434' => 'д', '\u0414' => 'Д',
    '\u0435' => 'е', '\u0415' => 'Е',
    '\u0451' => 'ё', '\u0401' => 'Ё',
    '\u0436' => 'ж', '\u0416' => 'Ж',
    '\u0437' => 'з', '\u0417' => 'З',
    '\u0438' => 'и', '\u0418' => 'И',
    '\u0439' => 'й', '\u0419' => 'Й',
    '\u043a' => 'к', '\u041a' => 'К',
    '\u043b' => 'л', '\u041b' => 'Л',
    '\u043c' => 'м', '\u041c' => 'М',
    '\u043d' => 'н', '\u041d' => 'Н',
    '\u043e' => 'о', '\u041e' => 'О',
    '\u043f' => 'п', '\u041f' => 'П',
    '\u0440' => 'р', '\u0420' => 'Р',
    '\u0441' => 'с', '\u0421' => 'С',
    '\u0442' => 'т', '\u0422' => 'Т',
    '\u0443' => 'у', '\u0423' => 'У',
    '\u0444' => 'ф', '\u0424' => 'Ф',
    '\u0445' => 'х', '\u0425' => 'Х',
    '\u0446' => 'ц', '\u0426' => 'Ц',
    '\u0447' => 'ч', '\u0427' => 'Ч',
    '\u0448' => 'ш', '\u0428' => 'Ш',
    '\u0449' => 'щ', '\u0429' => 'Щ',
    '\u044a' => 'ъ', '\u042a' => 'Ъ',
    '\u044b' => 'ы', '\u042b' => 'Ы',
    '\u044c' => 'ь', '\u042c' => 'Ь',
    '\u044d' => 'э', '\u042d' => 'Э',
    '\u044e' => 'ю', '\u042e' => 'Ю',
    '\u044f' => 'я', '\u042f' => 'Я',

   '\r' => '',
   '\n' => "\n",
   '\t' => ''
  );

  return strtr(
      $json_str,  
      $flip ? array_flip($cyr_chars) : $cyr_chars
    );
}

